const MAX_POKEMONS = 151
const MAX_TEAM = 6
const LIMIT_PAGE = 25
const BASE_URL_POKEMON = import.meta.env.VITE_API_POKEMON_URL
const BASE_URL_DB = import.meta.env.VITE_API_DB_URL

export { MAX_POKEMONS, MAX_TEAM, LIMIT_PAGE, BASE_URL_POKEMON, BASE_URL_DB }
